# -*- coding: utf-8 -*-
"""board.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12uGmiKLi1QYh3RDZ8ADX6cQ6Tufx3Ubm
"""

board = [["_", "_", "_"],
         ["_", "_", "_"],
         ["_", "_", "_"]]

def print_board():
  for i in board:                                                                                                                                                     
    print(i)

def check_mark(row, col):
  if board[row][col] == "_":
    return True
  else:
    return False

def place_mark(row, col, player_id):
  if player_id == 1:
    board[row][col] = "X"
  elif player_id == 2:
    board[row][col] = "O"


def check_win(player_id):
  if player_id == 1:
    if board[row][col] == "X":
      return True
    else:
      return False
  if player_id == 2:
    if board[row][col] == "O":
      return True
    else:
      return False

def main():
  print("Testing print_board")
  print_board()

  print("before place_mark, check_mark for 1, 1 is ", check_mark(1, 1))

  place_mark(1, 1, 1)
  print_board()
  print("after place_mark, check_mark for 1, 1 is ", check_mark(1, 1))

  place_mark(0, 2, 2)
  print_board()

main()